spring:
  dev-url: http://localhost:8080
  prod-url: https://exemple:com
  datasource:
    url: jdbc:h2:mem:car_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui.path: /swagger-ui
  api-docs:
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    filter: true